### ISSUE TITLE
Build Error

### ISSUE THREAD

**Issue by rumaysaalvina** [braintripping/lark#2]
compilation failed
{:tag :shadow.build.compiler/fail-many, :resource-ids ([:shadow.build.classpath/resource "cljs/core.cljs"] [:shadow.build.classpath/resource "devtools/context.cljs"] [:shadow.build.classpath/resource "devtools/defaults.cljs"]), :errors {[:shadow.build.classpath/resource "cljs/core.cljs"] #error {
 :cause nil
 :via
 [{:type clojure.lang.ExceptionInfo
   :message "failed to compile resource: [:shadow.build.classpath/resource \"cljs/core.cljs\"]"
   :data {:tag :shadow.build.compiler/compile-cljs, :resource-id [:shadow.build.classpath/resource "cljs/core.cljs"], :source-id [:shadow.build.classpath/resource "cljs/core.cljs"], :url #object[java.net.URL 0x2ce58f15 "jar:file:/home/man2/.m2/repository/org/clojure/clojurescript/1.10.439/clojurescript-1.10.439.jar!/cljs/core.cljs"], :file nil}
   :at [clojure.core$ex_info invokeStatic "core.clj" 4739]}
  {:type java.lang.NullPointerException
   :message nil
   :at [cljs.compiler$emit$fn__3144 invoke "compiler.cljc" 189]}]
 :trace
 [[cljs.compiler$emit$fn__3144 invoke "compiler.cljc" 189]
  [clojure.lang.Atom swap "Atom.java" 37]
  [clojure.core$swap_BANG_ invokeStatic "core.clj" 2344]
  [clojure.core$swap_BANG_ invoke "core.clj" 2337]
  [cljs.compiler$emit invokeStatic "compiler.cljc" 187]
  [cljs.compiler$emit invoke "compiler.cljc" 182]
  [shadow.build.compiler$eval12928$fn__12929 invoke "compiler.clj" 232]
  [clojure.lang.MultiFn invoke "MultiFn.java" 233]
  [shadow.build.compiler$do_compile_cljs_resource$fn__12991$fn__12994 invoke "compiler.clj" 454]
  [shadow.build.compiler$do_compile_cljs_resource$fn__12991 invoke "compiler.clj" 451]
  [shadow.build.compiler$do_compile_cljs_resource invokeStatic "compiler.clj" 414]
  [shadow.build.compiler$do_compile_cljs_resource invoke "compiler.clj" 376]
  [shadow.build.compiler$maybe_compile_cljs$fn__13077 invoke "compiler.clj" 694]
  [shadow.build.compiler$maybe_compile_cljs invokeStatic "compiler.clj" 693]
  [shadow.build.compiler$maybe_compile_cljs invoke "compiler.clj" 669]
  [shadow.build.compiler$par_compile_one invokeStatic "compiler.clj" 795]
  [shadow.build.compiler$par_compile_one invoke "compiler.clj" 750]
  [shadow.build.compiler$par_compile_cljs_sources$fn__13111$iter__13133__13137$fn__13138$fn__13139$fn__13140 invoke "compiler.clj" 868]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 657]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1965]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1965]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 661]
  [clojure.core$bound_fn_STAR_$fn__5471 doInvoke "core.clj" 1995]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [clojure.lang.AFn call "AFn.java" 18]
  [java.util.concurrent.FutureTask run "FutureTask.java" 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1149]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 624]
  [java.lang.Thread run "Thread.java" 748]]}, [:shadow.build.classpath/resource "devtools/context.cljs"] #error {
 :cause nil
 :via
 [{:type clojure.lang.ExceptionInfo
   :message "failed to compile resource: [:shadow.build.classpath/resource \"devtools/context.cljs\"]"
   :data {:tag :shadow.build.compiler/compile-cljs, :resource-id [:shadow.build.classpath/resource "devtools/context.cljs"], :source-id [:shadow.build.classpath/resource "devtools/context.cljs"], :url #object[java.net.URL 0x18b1bdf "jar:file:/home/man2/.m2/repository/binaryage/devtools/0.9.10/devtools-0.9.10.jar!/devtools/context.cljs"], :file nil}
   :at [clojure.core$ex_info invokeStatic "core.clj" 4739]}
  {:type java.lang.NullPointerException
   :message nil
   :at [cljs.compiler$emit$fn__3144 invoke "compiler.cljc" 189]}]
 :trace
 [[cljs.compiler$emit$fn__3144 invoke "compiler.cljc" 189]
  [clojure.lang.Atom swap "Atom.java" 37]
  [clojure.core$swap_BANG_ invokeStatic "core.clj" 2344]
  [clojure.core$swap_BANG_ invoke "core.clj" 2337]
  [cljs.compiler$emit invokeStatic "compiler.cljc" 187]
  [cljs.compiler$emit invoke "compiler.cljc" 182]
  [shadow.build.compiler$eval12928$fn__12929 invoke "compiler.clj" 232]
  [clojure.lang.MultiFn invoke "MultiFn.java" 233]
  [shadow.build.compiler$do_compile_cljs_resource$fn__12991$fn__12994 invoke "compiler.clj" 454]
  [shadow.build.compiler$do_compile_cljs_resource$fn__12991 invoke "compiler.clj" 451]
  [shadow.build.compiler$do_compile_cljs_resource invokeStatic "compiler.clj" 414]
  [shadow.build.compiler$do_compile_cljs_resource invoke "compiler.clj" 376]
  [shadow.build.compiler$maybe_compile_cljs$fn__13077 invoke "compiler.clj" 694]
  [shadow.build.compiler$maybe_compile_cljs invokeStatic "compiler.clj" 693]
  [shadow.build.compiler$maybe_compile_cljs invoke "compiler.clj" 669]
  [shadow.build.compiler$par_compile_one invokeStatic "compiler.clj" 795]
  [shadow.build.compiler$par_compile_one invoke "compiler.clj" 750]
  [shadow.build.compiler$par_compile_cljs_sources$fn__13111$iter__13133__13137$fn__13138$fn__13139$fn__13140 invoke "compiler.clj" 868]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 657]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1965]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1965]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 661]
  [clojure.core$bound_fn_STAR_$fn__5471 doInvoke "core.clj" 1995]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [clojure.lang.AFn call "AFn.java" 18]
  [java.util.concurrent.FutureTask run "FutureTask.java" 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1149]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 624]
  [java.lang.Thread run "Thread.java" 748]]}, [:shadow.build.classpath/resource "devtools/defaults.cljs"] #error {
 :cause nil
 :via
 [{:type clojure.lang.ExceptionInfo
   :message "failed to compile resource: [:shadow.build.classpath/resource \"devtools/defaults.cljs\"]"
   :data {:tag :shadow.build.compiler/compile-cljs, :resource-id [:shadow.build.classpath/resource "devtools/defaults.cljs"], :source-id [:shadow.build.classpath/resource "devtools/defaults.cljs"], :url #object[java.net.URL 0x1a34eb4 "jar:file:/home/man2/.m2/repository/binaryage/devtools/0.9.10/devtools-0.9.10.jar!/devtools/defaults.cljs"], :file nil}
   :at [clojure.core$ex_info invokeStatic "core.clj" 4739]}
  {:type java.lang.NullPointerException
   :message nil
   :at [cljs.compiler$emit$fn__3144 invoke "compiler.cljc" 189]}]
 :trace
 [[cljs.compiler$emit$fn__3144 invoke "compiler.cljc" 189]
  [clojure.lang.Atom swap "Atom.java" 37]
  [clojure.core$swap_BANG_ invokeStatic "core.clj" 2344]
  [clojure.core$swap_BANG_ invoke "core.clj" 2337]
  [cljs.compiler$emit invokeStatic "compiler.cljc" 187]
  [cljs.compiler$emit invoke "compiler.cljc" 182]
  [shadow.build.compiler$eval12928$fn__12929 invoke "compiler.clj" 232]
  [clojure.lang.MultiFn invoke "MultiFn.java" 233]
  [shadow.build.compiler$do_compile_cljs_resource$fn__12991$fn__12994 invoke "compiler.clj" 454]
  [shadow.build.compiler$do_compile_cljs_resource$fn__12991 invoke "compiler.clj" 451]
  [shadow.build.compiler$do_compile_cljs_resource invokeStatic "compiler.clj" 414]
  [shadow.build.compiler$do_compile_cljs_resource invoke "compiler.clj" 376]
  [shadow.build.compiler$maybe_compile_cljs$fn__13077 invoke "compiler.clj" 694]
  [shadow.build.compiler$maybe_compile_cljs invokeStatic "compiler.clj" 693]
  [shadow.build.compiler$maybe_compile_cljs invoke "compiler.clj" 669]
  [shadow.build.compiler$par_compile_one invokeStatic "compiler.clj" 795]
  [shadow.build.compiler$par_compile_one invoke "compiler.clj" 750]
  [shadow.build.compiler$par_compile_cljs_sources$fn__13111$iter__13133__13137$fn__13138$fn__13139$fn__13140 invoke "compiler.clj" 868]
  [clojure.lang.AFn applyToHelper "AFn.java" 152]
  [clojure.lang.AFn applyTo "AFn.java" 144]
  [clojure.core$apply invokeStatic "core.clj" 657]
  [clojure.core$with_bindings_STAR_ invokeStatic "core.clj" 1965]
  [clojure.core$with_bindings_STAR_ doInvoke "core.clj" 1965]
  [clojure.lang.RestFn invoke "RestFn.java" 425]
  [clojure.lang.AFn applyToHelper "AFn.java" 156]
  [clojure.lang.RestFn applyTo "RestFn.java" 132]
  [clojure.core$apply invokeStatic "core.clj" 661]
  [clojure.core$bound_fn_STAR_$fn__5471 doInvoke "core.clj" 1995]
  [clojure.lang.RestFn invoke "RestFn.java" 397]
  [clojure.lang.AFn call "AFn.java" 18]
  [java.util.concurrent.FutureTask run "FutureTask.java" 266]
  [java.util.concurrent.ThreadPoolExecutor runWorker "ThreadPoolExecutor.java" 1149]
  [java.util.concurrent.ThreadPoolExecutor$Worker run "ThreadPoolExecutor.java" 624]
  [java.lang.Thread run "Thread.java" 748]]}}}
ExceptionInfo: compilation failed
	clojure.core/ex-info (core.clj:4739)
	clojure.core/ex-info (core.clj:4739)
	shadow.build.compiler/par-compile-cljs-sources/fn--13111 (compiler.clj:881)
	shadow.build.compiler/par-compile-cljs-sources (compiler.clj:815)
	shadow.build.compiler/par-compile-cljs-sources (compiler.clj:808)
	shadow.build.compiler/compile-cljs-sources (compiler.clj:924)
	shadow.build.compiler/compile-cljs-sources (compiler.clj:914)
	shadow.build.compiler/compile-all (compiler.clj:1092)
	shadow.build.compiler/compile-all (compiler.clj:1003)
	shadow.build.api/compile-sources (api.clj:239)
	shadow.build.api/compile-sources (api.clj:231)
	shadow.build/compile (build.clj:357)
	shadow.build/compile (build.clj:348)
	shadow.cljs.devtools.server.worker.impl/build-compile (impl.clj:251)
	shadow.cljs.devtools.server.worker.impl/build-compile (impl.clj:237)
	shadow.cljs.devtools.server.worker.impl/eval15352/fn--15354 (impl.clj:552)
	clojure.lang.MultiFn.invoke (MultiFn.java:233)
	shadow.cljs.devtools.server.util/server-thread/fn--15090/fn--15091/fn--15099 (util.clj:294)
	shadow.cljs.devtools.server.util/server-thread/fn--15090/fn--15091 (util.clj:293)
	shadow.cljs.devtools.server.util/server-thread/fn--15090 (util.clj:266)
	java.lang.Thread.run (Thread.java:748)

**Comment by mhuebert** [comment]
Thanks @rumaysaalvina, this should be fixed now in 5c836f0. The problem was an old version of shadow-cljs that is incompatible with the latest versions of ClojureScript due to some backwards-incompatible changes in the compiler AST format.

**Comment by rumaysaalvina** [comment]
thanks @mhuebert, build works perfectly. thank you.
